name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ vars.PUBLISH_USER }}
          password: ${{ secrets.PUBLISH_TOKEN }}

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Build
        run: ./gradlew build

      - name: Build and push Docker image
        run: ./gradlew docker dockerPushVersion
        if: startsWith(github.ref, 'refs/tags/')
